version: "3.7"
services:
  bookle-nginx:
    image: nginx:latest
    container_name: bookle-nginx.docker
    ports:
      - "1212:80"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - "./site/dist:/var/www/html/bookle"
      - "./site/site.conf:/etc/nginx/conf.d/site.conf"
      - "./api:/var/www/html/api"
      - "./api/api.conf:/etc/nginx/conf.d/api.conf"
    networks:
      - bookle-network
    depends_on:
      - bookle-php
      - bookle-mysql
  bookle-site:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    image: bookle-site:latest
    container_name: bookle-site.docker
    ports:
      - "1414:8080"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - "./site:/var/www/html/site"
      - "./admin:/var/www/html/admin"
    networks:
      - bookle-network
  bookle-php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: bookle-php:latest
    container_name: bookle-php.docker
    volumes:
      - "./api:/var/www/html/api"
    networks:
      - bookle-network
  bookle-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: bookle
    container_name: bookle-mysql.docker
    networks:
      - bookle-network
    volumes:
      - "./mysql/data:/var/lib/mysql"
  bookle-phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - PMA_HOST=bookle-mysql.docker
      - PMA_USER=root
      - PMA_PASSWORD=bookle
      - MYSQL_ROOT_PASSWORD=bookle
    container_name: bookle-phpmyadmin.docker
    ports:
      - "1515:80"
    networks:
      - bookle-network
    depends_on:
      - bookle-mysql
networks:
  bookle-network:
    driver: bridge