version: "3.7"
services:
  bookle-nginx:
    image: nginx:alpine
    container_name: bookle-nginx.docker
    ports:
      - "1212:80"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - "./site/dist:/var/www/html/bookle"
      - "./site/server.conf:/etc/nginx/conf.d/server.conf"
    networks:
      - bookle-network
  bookle-site:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    image: bookle-site:latest
    container_name: bookle-site.docker
    ports:
      - "1414:8080"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - "./site:/var/www/html/site"
    networks:
      - bookle-network
  bookle-php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: bookle-php:latest
    container_name: bookle-php.docker
networks:
  bookle-network:
    driver: bridge