version: "3.7"
services:
  bookle-nginx:
    image: nginx:latest
    container_name: bookle-nginx.docker
    ports:
      - "1212:80"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - "./frontend/dist:/var/www/html/frontend"
      - "./frontend/server.conf:/etc/nginx/conf.d/server.conf"
    networks:
      - bookle-network
  bookle-frontend:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    image: bookle-frontend:latest
    container_name: bookle-frontend.docker
    ports:
      - "1414:8080"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - "./frontend:/var/www/html/frontend"
    networks:
      - bookle-network
  bookle-php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: bookle-php:latest
    container_name: bookle-php.docker
networks:
  bookle-network:
    driver: bridge